image:
  name: atlassian/default-image:2

release: &release
  step:
    name: Push and Tag
    image: python:3.6.7
    script:
      - pip install semversioner==0.6.16
      - ./ci-scripts/bump-version.sh
      - ./ci-scripts/docker-release.sh sonarsource/$BITBUCKET_REPO_SLUG
      - ./ci-scripts/git-push.sh
    services:
      - docker

build-docker-qa: &build-docker-qa
  step:
    name: Create and push Docker image for QA
    image: python:3.6.7
    script:
      - pip install semversioner==0.6.16
      - ./ci-scripts/bump-version.sh
      - ./ci-scripts/docker-release.sh sonarsource/$BITBUCKET_REPO_SLUG QA
    services:
      - docker

sbom: &sbom
  step:
    name: Generate sbom
    script:
      - export SYFT_VERSION=v0.45.1
      - export SYFT_INSTALLER_SHA256=a6dfabcd60ec8b09a8269d5efda8c797ad9657567cd723306f5cfc3fcb07b79b
      - curl -sSfL https://raw.githubusercontent.com/anchore/syft/$SYFT_VERSION/install.sh -o install.sh
      - echo "$SYFT_INSTALLER_SHA256  install.sh"|sha256sum -c -
      - sh ./install.sh $SYFT_VERSION
      - ./bin/syft sonarsource/$BITBUCKET_REPO_SLUG -o cyclonedx-json=sbom.json
    services:
      - docker
    artifacts:
      - sbom.json

pipelines:
  custom:
    release:
      - <<: *release
      - <<: *sbom
    build-docker-qa:
      - <<: *build-docker-qa
